package main

import (
	"errors"
	"time"
)

// ChatMessage describes the payload sent over WebSocket connections.
type ChatMessage struct {
	Type       string    `json:"type"`
	SenderID   int       `json:"sender_id"`
	ReceiverID int       `json:"receiver_id"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at,omitempty"`
}

const (
	defaultMessageType = "message"
)

// saveMessage persists a chat message to the database.
func saveMessage(msg ChatMessage) error {
	if msg.Content == "" || msg.ReceiverID == 0 || msg.SenderID == 0 {
		return errors.New("missing message fields")
	}

	// CreatedAt is generated by the database, but we keep the field on the struct
	// to send back to clients if they need it.
	_, err := DB.Exec(
		`INSERT INTO messages (sender_id, receiver_id, content) VALUES (?, ?, ?)`,
		msg.SenderID, msg.ReceiverID, msg.Content,
	)
	return err
}
